name: CI/CD Exercise

image: maven:3.8.1-jdk-11

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

before_script:
  - echo "Using Maven version:"
  - mvn -v

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  only:
    - merge_requests
    - master

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:
    - merge_requests
    - master
