name: CI/CD Exercise

image: maven:3.8.1-jdk-11

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

before_script:
  - echo "Using Maven version:"
  - mvn -v

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  only:
    - merge_requests
    - master

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:
    - merge_requests
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and test
        run: mvn clean verify

  quality:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run CheckStyle
        run: mvn checkstyle:check

